# Create VPC, subnets, route_tables.
# The absence or presense of subnets deletes or creates them respectively.
---
# Create base VPC configuration
- name: Provision VPC (AWS-VPC-EC2)
  local_action:  
    module: ec2_vpc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    instance_tenancy: default
    internet_gateway: True
    subnets: "{{ subnets }}"
    route_tables: "{{ route_tables }}"
    region: "{{ region }}"
  register: vpc
