# Create VPC, subnets, route_tables.
# The absence or presense of subnets deletes or creates them respectively.
---
# Create base VPC configuration
- name: Provision VPC (AWS-VPC-EC2)
  local_action:  
    module: ec2_vpc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    instance_tenancy: default
    internet_gateway: True
    subnets: "{{ subnets }}"
    route_tables: "{{ route_tables }}"
    region: "{{ region }}"
  register: vpc

- name: Initial VPC peering request
  local_action: command /usr/local/bin/aws ec2 create-vpc-peering-connection --vpc-id {{ vpc.vpc_id }} --peer-vpc-id {{ vpc_peer_vpc_id }} --peer-owner-id {{ vpc_peer_owner_id }} --profile {{ owner }}
  sudo: no
  when: vpc_peering == True and vpc_peer_vpc_id is defined
